#cmakedefine OTTER_INSTALL_PREFIX "@CMAKE_INSTALL_PREFIX@"
#cmakedefine OTTER_VERSION_MAIN "@OTTER_VERSION_MAIN@"
#cmakedefine OTTER_VERSION_WEEKLY "@OTTER_VERSION_WEEKLY@"
#cmakedefine OTTER_VERSION_CONTEXT "@OTTER_VERSION_CONTEXT@"
